### ISSUE TITLE
FromJSON / ToJSON missing for IPv6

### ISSUE THREAD

**Issue by dsvensson** [andrewthad/haskell-ip#18]
Like subject says, missing JSON functions for IPv6.

**Comment by dsvensson** [comment]
...also missing for Net.Types.IP, but maybe that's intentional?

**Comment by andrewthad** [comment]
Yeah, these should be there, but I never got around to it since I haven't actually ended up using these types as much in applications I work on. I would say that I'd take a PR, but I'm in the middle of refactoring some of the modules, so if anyone does want to PR this, wait a couple of hours before I push everything I've changed into master.

**Comment by dsvensson** [comment]
I'd be happy to contribute that, but I'm very new to Haskell so I'm mostly scratching my head wondering how to do that.

When looking at the [FromJSON for IPv4](https://github.com/andrewthad/haskell-ip/blob/master/src/Net/Types.hs#L149
), it looks like there's some duplication via [decodeIPv4TextEither](https://github.com/andrewthad/haskell-ip/blob/master/src/Net/Internal.hs#L56) compared to what is found in IPv4.hs. Why is that? Couldn't FromJSON just dispatch that to the same parser? ...and the IPv6 version could do a similar thing.

**Comment by andrewthad** [comment]
The module structure deserves some explanation. Basically, there are several options for how to structure modules in a library. Let's consider two such options.

1. Each exported module contains a type and all of its related functions
2. All type declarations go in a `Types` modules, and modules named after each type contain only functions related to the type.

Both options have their advantages. For this library, I chose the second one, because when using `ip`, I often want all of the types in scope unqualified, but I want always use the functions for working with them qualified. For example, the way I typically use `ip` looks something like this:

    import Net.Types (IPv4,IPv4Range,Mac)
    import qualified Net.IPv4 as I
    import qualified Net.IPv4 as R
    import qualified Net.Mac as M

If I had gone with option (1) for the module structure, I would need to do this instead:

    import Net.IPv4 (IPv4)
    import Net.IPv4 (IPv4Range)
    import Net.Mac (Mac)
    import qualified Net.IPv4 as I
    import qualified Net.IPv4 as R
    import qualified Net.Mac as M

Again, whether or not the structure I decided on is better depends very much on how the end user actually uses the library and what their preferences regarding qualified imports are.

Now, to get to your question: Why is does [`decodeIPv4TextEither`](https://github.com/andrewthad/haskell-ip/blob/958263e13a3cc269b06210c6108b7d30ed83dc1c/src/Net/Internal.hs#L56-L68) even exist? The problem is that the `FromJSON` instance needs to live in the same module as `IPv4` (to avoid orphan instances), but that instance needs to call the decode function, which lives in `Net.IPv4`. If we naively try to do this, we will create a cyclic import (since `Net.IPv4` definitely has to import `Net.Types`), which GHC complains about. So, we have to break up the cycle like this:

      +----------------------------------+
      |                                  v
    +----------+     +-----------+     +--------------+
    | Net.IPv4 | --> | Net.Types | --> | Net.Internal |
    +----------+     +-----------+     +--------------+

Both modules import `Net.Internal`, which has the meat of the ip decoding logic. It's a nasty module with a ton of top-level functions inside, but it works. Crucially, it doesn't actually use the `IPv4` type. The ip functions there works on `Word32`s, and since `IPv4` is just a newtype wrapper around `Word32`, we can use trivially use them in `Net.IPv4` and `Net.Types`.

So, the cause of this is that I cannot stand orphan instances, and I'm willing to move logic to around to avoid them. Notice that we only have to move things to `Net.Internal` when they are both (1) something needed by a typeclass instance and (2) something needed by a non-typeclass function we want to offer to end users.

**Comment by andrewthad** [comment]
I've added the `IPv6` instances with 4150ff7cb9a687a1ebdf7146e762a704b7a3c2fb

**Comment by andrewthad** [comment]
This has been released to hackage. Also, it's worth noting that I actually decided to change the structure of the data type definitions described in [my earlier comment](https://github.com/andrewthad/haskell-ip/issues/18#issuecomment-337440608). Now, all of the data type definitions live in the module named after them (`IPv4` is defined in `Net.IPv4`, etc.), and `Net.Types` simply re-exports all of these. It avoids the need for a `Net.Internal` module.
